Feature/progress bar cb
Maren-Osnabrug/InflightSalesExperience pull request #19
Opened 2017-12-05 14:25 UTC by zwiersj003

2017-12-05 14:47 UTC, Maren-Osnabrug requested changes

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +
whitespace

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +        flights()
these aren't descriptive method names

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +        products()
same as above

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +                    let flightnumber = Flight(snapshot: flight)
you are appending a flight, not a number

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +                    let products = Product(snapshot: product)
you are appending one product

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
>          return 130
use constant

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +            let flight = flightsArray[1]
why the second flight

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +        return 100
constant

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
>              let arr = snapshot.children.allObjects as NSArray
array of products?

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +                    if item.id == String(request.productId) {
brackets

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX/Cells/ProgressBarCell.swift
> +            progress = (Float(currentRevenue)/Float(flight.highestRevenue))
this line and the one below are the same in both statements, so they can be place above the if/else

2017-12-05 14:47 UTC, Maren-Osnabrug commented on ISX/ISX/Models/Flight.swift
> +        self.ref = snapshot.ref
this looks fine, like all the other models, but we might need to consider refactoring without force casting in the future

2017-12-05 14:56 UTC, robbym1991 requested changes

2017-12-05 14:56 UTC, robbym1991 commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +    func flights() {
duidelijkere methodenaame

2017-12-05 14:56 UTC, robbym1991 commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +                        self.flightsArray.append(flightnumber)
tab te ver

2017-12-05 14:56 UTC, robbym1991 commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +    func products() {
methodnaam kan beter

2017-12-05 14:56 UTC, robbym1991 commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
>          return 130
magic number

2017-12-05 14:56 UTC, robbym1991 commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
>          return 130
bijvoorbeeld beter om in Constants te verwerken

2017-12-05 14:56 UTC, robbym1991 commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +        if (flightsArray.count > 0 ){
spatie ){

2017-12-05 14:56 UTC, robbym1991 commented on ISX/ISX-CabinCrew/CabinCrewViewController.swift
> +        return 100
magic number

2017-12-06 09:10 UTC, Maren-Osnabrug approved these changes

2017-12-06 10:20 UTC, robbym1991 approved these changes

2017-12-06 10:21 UTC, merged